/* eslint-disable */
// GENERATED by scripts/gen-crds.mjs from service/crds/*.yaml. Do not edit.
//
// Edit the YAML under service/crds/ and run `node scripts/gen-crds.mjs`. The extension writes
// these definitions into the cluster from the browser (service.ts), because Rancher installs an
// extension chart as its UIPlugin alone and discards any CRDs bundled with it.
export const CRD_DEFINITIONS: Record<string, unknown>[] = [
  {
    "apiVersion": "apiextensions.k8s.io/v1",
    "kind": "CustomResourceDefinition",
    "metadata": {
      "name": "appinstances.appsplus.io"
    },
    "spec": {
      "conversion": {
        "strategy": "None"
      },
      "group": "appsplus.io",
      "names": {
        "categories": [
          "appsplus"
        ],
        "kind": "AppInstance",
        "listKind": "AppInstanceList",
        "plural": "appinstances",
        "shortNames": [
          "apinst"
        ],
        "singular": "appinstance"
      },
      "scope": "Cluster",
      "versions": [
        {
          "additionalPrinterColumns": [
            {
              "jsonPath": ".spec.app",
              "name": "App",
              "type": "string"
            },
            {
              "jsonPath": ".spec.namespace",
              "name": "Namespace",
              "type": "string"
            },
            {
              "jsonPath": ".status.bundleName",
              "name": "Bundle",
              "type": "string"
            },
            {
              "jsonPath": ".metadata.creationTimestamp",
              "name": "Age",
              "type": "date"
            }
          ],
          "name": "v1alpha1",
          "schema": {
            "openAPIV3Schema": {
              "properties": {
                "spec": {
                  "properties": {
                    "app": {
                      "description": "Name of the App this is an instance of.",
                      "type": "string"
                    },
                    "namespace": {
                      "description": "Namespace the rendered resources land in on each target.",
                      "type": "string"
                    },
                    "provisionCluster": {
                      "description": "Create a cluster for this instance rather than deploying to existing ones. The cluster is owned by the instance, so deleting the instance deletes it. An instance owns at most one cluster, and deploys only to that one.",
                      "properties": {
                        "enabled": {
                          "type": "boolean"
                        },
                        "name": {
                          "description": "Defaults to the instance name.",
                          "type": "string"
                        }
                      },
                      "type": "object"
                    },
                    "targets": {
                      "description": "Which existing clusters to deploy to.",
                      "items": {
                        "properties": {
                          "clusterGroup": {
                            "type": "string"
                          },
                          "clusterName": {
                            "type": "string"
                          }
                        },
                        "type": "object"
                      },
                      "type": "array"
                    },
                    "values": {
                      "description": "Overrides the App's values. Substituted into templates as ${key}.",
                      "type": "object",
                      "x-kubernetes-preserve-unknown-fields": true
                    }
                  },
                  "required": [
                    "app"
                  ],
                  "type": "object"
                },
                "status": {
                  "type": "object",
                  "x-kubernetes-preserve-unknown-fields": true
                }
              },
              "type": "object"
            }
          },
          "served": true,
          "storage": true,
          "subresources": {
            "status": {}
          }
        }
      ]
    }
  },
  {
    "apiVersion": "apiextensions.k8s.io/v1",
    "kind": "CustomResourceDefinition",
    "metadata": {
      "name": "apps.appsplus.io"
    },
    "spec": {
      "conversion": {
        "strategy": "None"
      },
      "group": "appsplus.io",
      "names": {
        "categories": [
          "appsplus"
        ],
        "kind": "App",
        "listKind": "AppList",
        "plural": "apps",
        "shortNames": [
          "apapp"
        ],
        "singular": "app"
      },
      "scope": "Cluster",
      "versions": [
        {
          "additionalPrinterColumns": [
            {
              "jsonPath": ".status.templateCount",
              "name": "Templates",
              "type": "integer"
            },
            {
              "jsonPath": ".metadata.creationTimestamp",
              "name": "Age",
              "type": "date"
            }
          ],
          "name": "v1alpha1",
          "schema": {
            "openAPIV3Schema": {
              "properties": {
                "spec": {
                  "properties": {
                    "clusterTemplate": {
                      "description": "A provisioning.cattle.io Cluster manifest, for instances of this app that provision their own. Rendered with the same values as the templates above. Only its spec is used; name, workspace and ownership belong to the instance.",
                      "type": "string"
                    },
                    "defaultTargets": {
                      "items": {
                        "properties": {
                          "clusterName": {
                            "type": "string"
                          }
                        },
                        "type": "object"
                      },
                      "type": "array"
                    },
                    "description": {
                      "type": "string"
                    },
                    "templates": {
                      "description": "The chart. Each entry is one YAML file applied to every target.",
                      "items": {
                        "properties": {
                          "content": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "name",
                          "content"
                        ],
                        "type": "object"
                      },
                      "type": "array"
                    },
                    "valueLabels": {
                      "description": "Human-readable names for the keys in values, shown on the install form. A key with no label is shown as itself.",
                      "type": "object",
                      "x-kubernetes-preserve-unknown-fields": true
                    },
                    "values": {
                      "description": "Default values, substituted into templates as ${key}. The keys are the app's declared parameters - only these (and the built-ins) are ever substituted, so a template's own ${...} syntax survives rendering.",
                      "type": "object",
                      "x-kubernetes-preserve-unknown-fields": true
                    }
                  },
                  "type": "object"
                },
                "status": {
                  "type": "object",
                  "x-kubernetes-preserve-unknown-fields": true
                }
              },
              "type": "object"
            }
          },
          "served": true,
          "storage": true,
          "subresources": {
            "status": {}
          }
        }
      ]
    }
  }
];
