// Bakes the two CRDs into the bundle as crds.generated.ts.
//
// The extension creates its own CRDs on load (service.ts ensureService), the same way it creates
// its service - Rancher installs an extension chart as the UIPlugin only and strips everything
// else, so the CRDs cannot travel in the chart and have to be written from the browser. Their
// definitions therefore have to travel inside the bundle, like the service source does.
//
//   node scripts/gen-crds.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const yaml = require('js-yaml');

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(here, '..', 'service', 'crds');
const OUT = path.join(here, '..', 'crds.generated.ts');

const defs = fs.readdirSync(dir)
  .filter((f) => f.endsWith('.yaml'))
  .sort()
  .map((f) => yaml.load(fs.readFileSync(path.join(dir, f), 'utf8')));

fs.writeFileSync(OUT, `/* eslint-disable */
// GENERATED by scripts/gen-crds.mjs from service/crds/*.yaml. Do not edit.
//
// Edit the YAML under service/crds/ and run \`node scripts/gen-crds.mjs\`. The extension writes
// these definitions into the cluster from the browser (service.ts), because Rancher installs an
// extension chart as its UIPlugin alone and discards any CRDs bundled with it.
export const CRD_DEFINITIONS: Record<string, unknown>[] = ${ JSON.stringify(defs, null, 2) };
`);

console.log(`crds: ${ defs.length } definitions -> crds.generated.ts`);
