// Bakes the service's source into the bundle as service.generated.ts.
//
// The service runs from a ConfigMap this extension writes, so its source has to travel inside
// the bundle - and a `raw-loader!` import would tie that to one webpack config surviving in a
// build this repo does not own. The Studio does the same thing for the same reason
// (scripts/gen-extension-seed.mjs); a real file under service/ that is linted and reads like the
// script it is, generated into a string, and the output committed so normal builds never run
// this.
//
//   node scripts/gen-service.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SOURCE = path.join(here, '..', 'service', 'server.mjs');
const OUT = path.join(here, '..', 'service.generated.ts');

const source = fs.readFileSync(SOURCE, 'utf8');

fs.writeFileSync(OUT, `/* eslint-disable */
// GENERATED by scripts/gen-service.mjs from service/server.mjs. Do not edit.
//
// Edit service/server.mjs and run \`node scripts/gen-service.mjs\`. The extension writes this
// string into the ConfigMap the service pod runs from, so a change here that is not generated
// is a change that never reaches the cluster.
export const SERVICE_SOURCE = ${ JSON.stringify(source) };
`);

console.log(`service: ${ (source.length / 1024).toFixed(1) } KiB -> service.generated.ts`);
